version: 2
jobs:
    build:
        docker:
        - image: andreacensi/duckietown-xenial-kinetic:20
          environment:
              COLUMNS: 160
              NODE_PATH: /root/project/node_modules
              MPLBACKEND: agg

        resource_class: large

        steps:
        - checkout
        - run:
            name: NPM
            command: |
                curl -sL https://deb.nodesource.com/setup_6.x | bash
                apt install -y nodejs node-less
                npm install MathJax-node jsdom@9.3 less

        - run:
            name: fonts
            command: |
                apt-get install -y sudo
                make install-fonts

        - run:
            name: Setup MCDP
            command: |
                make install-ubuntu16

        - run:
            name: Check Programs
            command: |
                make check-programs

        - run:
            name: Checkout duckietown repository
            command: |
                git clone -b master --depth 1 git@github.com:duckietown/Software /tmp/git_repos/duckietown/Software/master
                ln -s /tmp/git_repos/duckietown/Software/master/ duckietown

        - run:
            name: Synchronize Wordpress
            command: |
                make db.related.yaml

        - run:
            name: Compile all books
            command: |
                echo "config colorize 0" > .compmake.rc
                ONLY_FOR_REFS=1 make -j4 book-code_docs books

        - run:
            name: Compile all books again to get cross references
            command: |
                make -j4 book-code_docs books

        - run:
            name: Create index of webpage
            command: |
              make summaries

        - run:
            when: always
            name: Package artifacts
            command:  |
                make package-artifacts

        - store_artifacts:
              path: out/package.tgz
              destination: out/package.tgz

        - test-results-store:
            path: duckuments-dist/junit

        - store_artifacts:
              path: duckuments-dist
              destination: duckuments-dist
